site_url: "https://www.madebysurface.co.uk"
publish_mode: editorial_workflow
media_folder: "src/assets/images"
public_folder: "/images"
show_preview_links: false

backend:
  name: git-gateway
  branch: master

local_backend:
  url: http://localhost:8082/api/v1

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - name: "index"
        label: "Homepage"
        file: "src/index.md"
        slug: "{{slug}}"
        create: false
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Testimonial #1", name: "testimonial_1", widget: "relation", collection: "testimonials", valueField: "{{slug}}", searchFields: ["author"], displayFields: ["{{author}} – ({{slug}})"]}
          - {label: "Testimonial #2", name: "testimonial_2", widget: "relation", collection: "testimonials", valueField: "{{slug}}", searchFields: ["author"], displayFields: ["{{author}} – ({{slug}})"]}
          - {label: "Testimonial #3", name: "testimonial_3", widget: "relation", collection: "testimonials", valueField: "{{slug}}", searchFields: ["author"], displayFields: ["{{author}} – ({{slug}})"]}
          - {label: "Testimonial #4", name: "testimonial_4", widget: "relation", collection: "testimonials", valueField: "{{slug}}", searchFields: ["author"], displayFields: ["{{author}} – ({{slug}})"]}

  - name: "testimonials"
    label: "Testimonials"
    folder: "src/_collections/testimonials"
    slug: "{{slug}}"
    identifier_field: author
    preview_path: testimonials/{{slug}}
    create: true
    delete: true
    sortableFields: ["order", "author"]
    fields:
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Company", name: "org", widget: "string", required: false}
      - {label: "Enabled", name: "enabled", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "expertise"
    label: "Expertise"
    folder: "src/_collections/expertise"
    slug: "{{slug}}"
    identifier_field: title
    preview_path: expertise/{{slug}}
    create: true
    delete: true
    sortableFields: ["order", "title"]
    fields:
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "playground"
    label: "Playground"
    folder: "src/_collections/playground"
    slug: "{{slug}}"
    identifier_field: title
    preview_path: playground/{{slug}}
    create: true
    delete: true
    sortableFields: ["order", "title"]
    fields:
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Enabled", name: "enabled", widget: "boolean"}
      - {label: "Title", name: "title", widget: "string"}

  - label: "Configuration"
    name: "config"
    editor:
      preview: false
    files:
      - label: "Site Data"
        name: "site_data"
        file: "src/_data/site.json"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Summary", name: "summary", widget: "string"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telephone", name: "telephone", widget: "string"}
